/* ŒILLETS — textes français. t(cle, variables) remplace {var}. */
const COPY = (() => {
  'use strict';
  const T = {
    titre: 'ŒILLETS', sous_titre: 'Marais de Kerbrun. Juin.', garde_toucher: 'Toucher pour ouvrir le carnet',
    bandeau_accelere: 'Première journée, en accéléré', bandeau_fin: 'Le marais vit maintenant au rythme de la mer. Prochaine pleine mer : {heure}. {prevision}',
    btn_carnet: 'Carnet', btn_cooperative: 'Coopérative', btn_creuser: 'Creuser', btn_vendre: 'Vendre', btn_rhabiller: 'Rhabiller · 60 €',
    btn_mettre_en_eau: 'Mettre en eau', btn_lever_eau: 'Lever l’eau', btn_fermer_marais: 'Fermer le marais', btn_ouvrir_saison: 'Ouvrir la saison',
    btn_voir_marais: 'Voir le marais', btn_confirmer: 'Creuser ici', btn_annuler: 'Laisser', btn_fermer: 'Retour', btn_retour: 'Retour au marais',
    hud_pleine_mer: 'Pleine mer {heure}', hud_seuil: 'seuil', hud_reserve: 'Réserve {jours} j', hud_mulon: '{kg} kg au mulon',
    type_vasiere: 'Vasière', type_cobier: 'Cobier', type_fare: 'Fare', type_aderne: 'Aderne', type_oeillet: 'Œillet',
    fiche_niveau: 'Niveau {cm} cm', fiche_salinite: 'Salinité {gl} g/L', fiche_temperature: 'Eau à {c} °C', fiche_argile: 'Argile {pct} %',
    fiche_algues: 'Eaux {etat}', fiche_sel: 'Sel couché {kg} kg', fiche_fleur: 'Fleur en surface {kg} kg', fiche_surface: '{n} part{s} d’eau',
    fiche_trappe: 'Trappe {direction} : {etat}, {debit} cm/h', fiche_projection_saturation: 'Saturé vers {heure}', fiche_projection_sec: 'À sec dans {h} h',
    fiche_projection_stable: 'Niveau tenu par l’amont', fiche_a_sec: 'À sec depuis {h} h', fiche_fissure: 'L’argile fissure : la parcelle fuit.',
    fiche_vasiere: 'Profondeur {cm} cm sur {max} cm · étier {etat}', fiche_croute: 'Croûte perdue {kg} kg : il manque un œillet en aval.',
    creuser_titre: 'Creuser en {r}·{c}', creuser_prix: '{type} · {prix} €', creuser_vasiere: 'Agrandir la vasière · {prix} € · réserve +50 %, étier élargi',
    creuser_vasiere_max: 'La vasière est à sa taille maximale.',
    creuser_impossible_denivele: 'Trop de dénivelé : il faut une aderne ou un fare entre les deux.',
    creuser_impossible_amont: 'Aucune eau en amont : rien ne viendrait remplir cette parcelle.',
    creuser_impossible_chapelet: 'Trop loin de l’aderne : cet œillet s’assécherait.',
    creuser_impossible_argent: 'Il manque {eur} €. Le marais y pourvoira.', creuser_impossible_place: 'Plus de terre libre. La commune en accordera à l’hiver.',
    creuser_conseil_oeillet: 'Un œillet rend ce que sa voisine lui apporte.', creuser_conseil_cobier: 'Un cobier garde l’eau pour les mortes-eaux.',
    creuser_conseil_fare: 'Un fare chauffe l’eau avant les adernes.', creuser_conseil_aderne: 'Une aderne tient la saumure rose et nourrit trois œillets.',
    creuser_aide: 'Touche une case libre, hachurée en jaune. Les trappes se créent fermées.',
    coop_etiquette: 'GROS SEL 0,80 €/kg · FLEUR DE SEL 12 €/kg · prix de la saison', coop_vente: '{kg} kg × 0,80 € = {eur} €',
    coop_vente_fleur: '+ {kg} kg de fleur × 12 € = {eur} €', coop_vide: 'Le mulon est vide. Tire le sel d’un geste sur un œillet blanc.',
    coop_clapet: 'La mer n’emportera plus ton eau : l’étier se ferme seul quand elle redescend.',
    coop_barometre: 'La courbe des 24 prochaines heures. La pluie se lit avant de tomber.',
    coop_lousse: 'Pour écumer la fleur de sel les soirs chauds et calmes, entre 15 h et 20 h.',
    coop_rhabillage: 'Rhabillage d’un talus · 60 € — depuis la fiche d’une parcelle fissurée.',
    coop_mur_vide: 'Aucun sac encore. Le premier sera pochoiré à l’hivernage.', coop_possede: 'Acquis', coop_acheter: 'Acheter · {prix} €',
    sac_record: 'SAISON {n} · {climat} · {tonnes} t · {record} kg/œillet/jour',
    marge_ouvre_etier: 'La mer monte. Ouvre l’étier.', marge_eaux_vieilles: 'Le vieux Le Goff t’a laissé ses eaux vieilles : le fare est violet, l’aderne encore rose.',
    marge_ferme_etier: 'L’eau repart avec la mer. Ferme l’étier.', marge_descendre: 'Fais descendre l’eau : ouvre les trappes, de la vasière jusqu’à l’œillet.',
    marge_tirer: 'Le sel est là. Tire-le avec le las, d’un geste.', marge_porter: 'Porte-le à la coopérative.', marge_remonte: 'La mer remonte. Reprends de l’eau.',
    marge_pluie: 'La pluie dissout. Avant la pluie : tire le sel, ferme les trappes des adernes.', marge_fleur: 'Soir chaud et calme : écume la fleur avant 20 h.',
    marge_reserve: 'Mortes-eaux dans {j} jours : la réserve tiendra {jours} jours.', marge_a_sec: 'L’œillet {n} est à sec depuis {h} h.',
    marge_croute: 'Le {type} {n} croûte : il lui manque un œillet.', marge_mise_en_eau: 'Il est tard. Mettre le marais en eau avant de partir ?',
    marge_rien: 'Rien à faire. Regarde l’eau.', marge_sel: '{kg} kg de sel attendent dans l’œillet {n}.', marge_pluie_vient: 'Le baromètre baisse : la pluie vient. Tire le sel.',
    marge_creuser: 'Tu as {eur} € : de quoi creuser.', marge_fin_journee: 'Le marais vit au rythme de la mer. Prochaine pleine mer : {heure}.',
    marge_hiver: 'L’eau d’hiver couvre le marais. Redessine-le, puis ouvre la saison.',
    carnet_titre: 'Carnet', carnet_titre_jour: '{jour} · lune {phase}', carnet_marees: 'Pleines mers : {h1} et {h2}. La mer {etat} le seuil.',
    carnet_marees_etats: ['franchira largement', 'franchira de peu', 'n’atteindra pas'],
    carnet_prevision: '{prevision} jusqu’à {heure}.', carnet_reserve: 'Réserve : {jours} jours d’eau.',
    carnet_record: 'Cette saison : {kg} kg par œillet et par jour. Record : {best}.', carnet_vide: 'Rien d’écrit encore. Le marais parlera le premier.',
    carnet_saison: 'Saison {n} · {climat} · jour {jour}', carnet_observations: 'Observations', carnet_saisons_passees: 'Saisons passées',
    carnet_fermer_trop_tot: 'On ne ferme pas avant la mi-saison (jour 14).', carnet_premiere_page: 'Pleines mers : {h1} et {h2}. {prevision} Clapet d’étier : 25 €. La mer n’emportera plus ton eau. Creuser un second œillet : 60 €.',
    obs_meilleur_oeillet: 'L’œillet {n} a fait {kg} kg hier.', obs_ratio: 'Tu as {aup} parts d’eau en amont pour {n} œillet{s}. Vers six pour un, ils tournent au plein.',
    obs_croute: 'Un bassin a dépassé 260 g/L : {kg} kg se sont perdus en croûte. Un œillet de plus l’aurait pris.',
    obs_sec: 'L’œillet {n} est resté à sec {h} h. Il manque une aderne pour le nourrir.',
    obs_pluie: 'La pluie a redissous {kg} kg dans les œillets non tirés.', obs_rose: 'L’aderne {n} est rose depuis {j} jours : ses algues font évaporer un quart plus vite.',
    obs_mortes_eaux: 'Mortes-eaux : la vasière est tombée à {cm} cm. Un cobier de plus aurait tenu.',
    obs_fleur: '{kg} kg de fleur écumés cette saison : {eur} €. Autant que {kg_gros} kg de gros sel.',
    obs_premiere: 'Première journée : {kg} kg tirés, {eur} €. L’aderne a tenu son rose malgré l’averse.',
    retour_titre: 'Depuis {jour}', retour_corps: '{n_marees} marée{s1}, {averses}, {kg} kg de gros sel formés, {fleur} kg de fleur en surface.',
    retour_averses: '{n} averse{s} ({detail})', retour_detail_pluie: '{jour} {heure}, {kg} kg redissous', retour_aucune_averse: 'pas une goutte',
    retour_ligne_aderne: 'L’aderne {n} est restée rose.', retour_ligne_sec: 'L’œillet {n} est à sec depuis {h} h.',
    retour_en_eau: 'Le marais était en eau : rien n’a bougé, rien ne s’est fissuré.',
    retour_hivernage: 'La lune a fait son tour pendant ton absence. L’hiver a noyé le marais : {tonnes} t cette saison. Le rhabillage t’attend.',
    mise_en_eau_confirm: 'Mettre tout le marais en eau ? Les œillets seront noyés à 8 cm, les trappes ouvertes, l’argile à l’abri. Le sel reviendra quand tu lèveras l’eau.',
    lever_eau_confirm: 'Lever l’eau : les œillets retrouvent 2 cm, le surplus retourne aux adernes.',
    fermer_confirm: 'Fermer le marais au jour {j} ? L’hiver noiera les bassins. Tu gardes {eur} €, tes parcelles saines, tes outils et ton carnet. L’eau, la saumure et les algues repartent de zéro. La commune accorde deux rangées de plus.',
    hivernage_titre: 'Hivernage', hivernage_corps: 'Saison {n}, {climat}. {tonnes} t, {record} kg par œillet et par jour. {perdues}',
    hivernage_perdues: '{n} parcelle{s} fissurée{s} rendue{s} à la vase.', hivernage_aucune_perdue: 'Aucune parcelle perdue.',
    rhabillage_titre: 'Rhabillage d’hiver', rhabillage_compteur: '{n} parcelle{s} à placer · {rows} rangées',
    rhabillage_aide: 'Touche une case pour changer son type ou la rendre à la vase, touche une case libre pour y poser une parcelle. Tout est gratuit : c’est ton argile.',
    rhabillage_probleme: '{n} parcelle{s} sans eau en amont (hachurée{s} en rouge). Déplace-la ou donne-lui un bassin voisin.',
    climat_annonce: 'L’an prochain : {climat}.',
    climats: { ordinaire: '2012, été ordinaire', secheresse: '1976, été de sécheresse', pourri: '1983, été pourri', canicule: '2003, canicule', vent: '1999, été de vent' },
    climat_effets: { ordinaire: 'Rien de particulier.', secheresse: '+3 °C, pluie rare, un peu de vent.', pourri: '−2 °C, pluie dès que le baromètre fléchit.', canicule: '+5 °C, l’argile fissure deux fois plus vite, fleur presque chaque soir.', vent: 'Vent soutenu : évaporation forte, fleur rare.' },
    sauvegarde_perdue: 'Le carnet a été mouillé : nouvelle page. Le marais recommence en juin.',
    lunes: ['nouvelle', 'premier croissant', 'premier quartier', 'gibbeuse croissante', 'pleine', 'gibbeuse décroissante', 'dernier quartier', 'dernier croissant'],
    previsions: { beau: 'Il fera beau', couvert: 'Le temps se couvre', pluie: 'Pluie probable', vent: 'Vent fort', fleur: 'Soir à fleur' },
    algues_etats: ['claires', 'qui rosissent', 'roses', 'rose vif'],
    directions: { N: 'nord', S: 'sud', E: 'est', O: 'ouest' },
    etier: 'Étier', etier_ouvert: 'ouvert', etier_ferme: 'fermé', clapet_court: 'clapet',
    glyphes: { soleil: '☼', nuage: '☁', pluie: '☂', lune: '☾' },
    objets: { clapet: 'Clapet d’étier', barometre: 'Baromètre enregistreur', lousse: 'Lousse à fleur' },
    lousse_absente: 'Il te faut une lousse pour écumer la fleur (coopérative, 120 €).',
    sac_vide: 'premier sac à l’hivernage',
  };
  const DICTONS = [
    'À marée haute on prend, à marée basse on attend.', 'Quand l’eau rosit, le sel n’est pas loin.', 'La nuit, l’eau se repose.',
    'Vent d’est, sel de fête.', 'Baromètre qui tombe, sel qu’on rentre.', 'Un œillet ne rend que ce qu’on lui porte.', 'Six parts d’eau pour une part de sel.',
    'Aux mortes-eaux, le marais boit dans ses poches.', 'Vive-eau de lune neuve, vasière qui déborde.', 'Argile sèche, talus qui pleure.',
    'La fleur vient au soir, quand le vent dort.', 'Chapelet trop long, dernier grain à sec.', 'Eaux vieilles au fare, printemps au marais.',
    'Un fare qui blanchit a trop peu d’enfants.', 'Septembre ferme ce que juin a ouvert.', 'Ce que la lune donne, la lune reprend.',
  ];
  function t(key, vars) {
    let s = T[key];
    if (s == null) return key;
    if (typeof s !== 'string') return s;
    if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] != null ? vars[k] : m));
    return s;
  }
  const pl = (n) => (n > 1 ? 's' : '');
  return { T, DICTONS, t, pl };
})();
